name: llvm_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-322.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.6
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  characters: ^1.3.0
  collection: ^1.17.1
  ffi: ^2.0.1
  file: ^6.1.4
  path: ^1.8.3
