name: llvm_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.2
  characters: ^1.3.0
  collection: ^1.17.1
  equatable: ^2.0.5
  ffi: ^2.1.2
  file: any
  meta: ^1.9.0
  nop: ^0.1.0+1
  path: ^1.8.3
